[build]
providers = ['python']

[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Python build complete"']

[start]
cmd = 'python main.py'

[variables]
PYTHONPATH = '/app'