version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: eco-tracker-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - IS_DOCKER=true
      - SECRET_KEY=${SECRET_KEY:-eco-tracker-secret-dev-key}
    volumes:
      - ./Backend:/app
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

  # Uncomment if you want to run the frontend in Docker too
  # frontend:
  #   build:
  #     context: ./Website
  #     dockerfile: Dockerfile
  #   container_name: eco-tracker-frontend
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - VITE_API_URL=http://backend:5000
  #   depends_on:
  #     - backend

volumes:
  backend_data:
