# DSP Eco Tracker - Netlify Configuration
[build]
  base = "frontend/website"
  publish = "dist"
  command = "npm run build"

# Production API redirects (update with your domain)
[[redirects]]
  from = "/api/*"
  to = "https://api.your-domain.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/estimate_emissions"
  to = "https://api.your-domain.com/estimate_emissions"
  status = 200
  force = true

[[redirects]]
  from = "/predict"
  to = "https://api.your-domain.com/predict"
  status = 200
  force = true

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"



