services:
  - type: web
    name: dsp-backend
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: gunicorn backend.api.app:app
    envVars:
      - key: FLASK_ENV
        value: production
    buildFilter:
      paths:
        - backend/**
